AddModelVirtualAttributeCheck: { }
AlwaysAddDbIndexCheck: { }
#CheckSaveReturnValueCheck: { }
#CheckDestroyReturnValueCheck: { }
DefaultScopeIsEvilCheck: { }
DryBundlerInCapistranoCheck: { }
#HashSyntaxCheck: { }
IsolateSeedDataCheck: { }
KeepFindersOnTheirOwnModelCheck: { }
LawOfDemeterCheck: { }
#LongLineCheck: { max_line_length: 80 }
MoveCodeIntoControllerCheck: { }
MoveCodeIntoHelperCheck: { array_count: 3 }
MoveCodeIntoModelCheck: { use_count: 2 }
MoveFinderToNamedScopeCheck: { }
MoveModelLogicIntoModelCheck: { use_count: 4 }
NeedlessDeepNestingCheck: { nested_count: 2 }
NotRescueExceptionCheck: { }
NotUseDefaultRouteCheck: { }
NotUseTimeAgoInWordsCheck: { }
OveruseRouteCustomizationsCheck: { customize_count: 3 }
ProtectMassAssignmentCheck: { }
RemoveEmptyHelpersCheck: { }
#RemoveTabCheck: { }
RemoveTrailingWhitespaceCheck: { }
RemoveUnusedMethodsInControllersCheck: { except_methods: [] }
RemoveUnusedMethodsInHelpersCheck:
  except_methods:
    - ApplicationHelper#masked_msisdn # To be fixed/refactored in separate MR next week
RemoveUnusedMethodsInModelsCheck:
  except_methods:
    - Auth::PasswordResetRequest#used! # To be fixed/refactored in separate MR next week
    - Auth::PasswordResetRequest#partial_url_token # To be fixed/refactored in separate MR next week
    - Auth::PasswordResetRequest#delivery_method_options # To be fixed/refactored in separate MR next week
    - Auth::User::OtpOptions#mask_email # Used in the same class via send
    - Auth::User::OtpOptions#mask_mobile # Used in then same class via send
    - ApplicationRecord#event_store_stream # Used in tests
    - Tenant::CustomLabel::I18nBackend#translations
    - Tenant::CustomLabel::I18nBackend#init_translations
    - Tenant::CustomLabel::I18nBackend#lookup
    - Communication::Scheduler#schedule # soon to be used
    - Communication::MessageLogEntry#collaborator_id # soon to be used
    - Communication::TemplateRender#remove_key # soon to be used
    - Communication::TemplateRender#prepare_attachments # soon to be used
    - Tenant::IntroImage#store_dir # Used by carrierwave
    - Tenant#brand_logo_will_change! # Used by carrierwave
    - Tenant#store_dir # Used by carrierwave
    - Tenant#extension_whitelist # Used by carrierwave
ReplaceComplexCreationWithFactoryMethodCheck: { attribute_assignment_count: 2 }
ReplaceInstanceVariableWithLocalVariableCheck: { }
RestrictAutoGeneratedRoutesCheck: { }
SimplifyRenderInControllersCheck: { }
SimplifyRenderInViewsCheck: { }
#UseBeforeFilterCheck: { customize_count: 2 }
UseModelAssociationCheck: { }
# UseMultipartAlternativeAsContentTypeOfEmailCheck: { }
#UseParenthesesInMethodDefCheck: { }
UseObserverCheck: { }
UseQueryAttributeCheck: { }
UseSayWithTimeInMigrationsCheck: { }
UseScopeAccessCheck: { }
UseTurboSprocketsRails3Check: { }
