# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7877250b9e330ae176a4b3df1fd52bd9c23e61c8a90450e1464423014905e2e23f2044f77efda2cc7c3621db204c1a7f93c8e79db8b0fce6777cf5bbfe82a33c

test:
  secret_key_base: a39579bb932b0da1ffb350374638f63f96f411b18a397af222e1ea9d2ea2239a4073d1861e5a728059cf5b031ccc992cf76e11e01a3401cbcfe5e0a50f48d14f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
